services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=myjavatutotabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5433:5432"
